"""Build the nine paper tables as CSV + MDPI-compatible booktabs .tex.

Every value is copied or arithmetically derived from a file listed in
``analysis/README.md``.  Nothing is estimated: a value that is not on disk is
written as the literal ``[MISSING: ...]`` string.

Run:  python build_tables.py
"""

from __future__ import annotations

import json
import math

import numpy as np
import pandas as pd

import config as C
import loaders as L
from extract_provenance import build_provenance

# ==========================================================================
# LaTeX emission
# ==========================================================================

_ESCAPE = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    # Greek letters are written plainly in the CSVs (CLAUDE.md S11) and become
    # proper math on the way into LaTeX.
    "\u03b5": r"$\varepsilon$", "\u03b4": r"$\delta$", "\u0394": r"$\Delta$",
    "\u03c1": r"$\rho$",
}


def tex_escape(text: str) -> str:
    """Escape a plain-text cell for LaTeX.

    Cells are escaped unconditionally; anything that must reach LaTeX as markup
    (URLs, math, significance stars) is declared via ``raw_columns`` on
    ``write_table`` instead of being sniffed out of the string, which is what
    previously mangled ``$N$`` into ``\\$N\\$``.
    """
    return "".join(_ESCAPE.get(ch, ch) for ch in str(text))


def fmt(value, nd: int = 4, raw: bool = False) -> str:
    """Format a cell for LaTeX. Missing/conflict markers survive verbatim."""
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return C.MISSING.format(what="value absent from source")
    if isinstance(value, str):
        return value if raw else tex_escape(value)
    if isinstance(value, (int, np.integer)):
        return f"{int(value):,}"
    return f"{float(value):.{nd}f}"


def write_table(name: str, df: pd.DataFrame, caption: str, note: str,
                col_spec: str | None = None, nd: int = 4,
                tex_columns: list[str] | None = None,
                headers: dict[str, str] | None = None,
                tex_df: pd.DataFrame | None = None,
                raw_columns: set[str] | None = None) -> None:
    """Write ``tables/csv/<name>.csv`` and ``tables/tex/<name>.tex``.

    ``df`` is always what lands in the CSV.  ``tex_df`` lets a table present a
    different *rendering* of the same values in LaTeX (URL macros, significance
    stars); it never introduces a value that is not in ``df``.
    """
    C.TABLES_CSV.mkdir(parents=True, exist_ok=True)
    C.TABLES_TEX.mkdir(parents=True, exist_ok=True)
    df.to_csv(C.TABLES_CSV / f"{name}.csv", index=False)

    base = tex_df if tex_df is not None else df
    tdf = base[tex_columns] if tex_columns else base
    headers = headers or {}
    raw_columns = raw_columns or set()
    spec = col_spec or "l" * len(tdf.columns)

    lines = []
    env = "table"
    lines.append("%% Auto-generated by analysis/src/build_tables.py -- do not edit by hand.")
    lines.append("%% MDPI booktabs fragment; \\input{} it from the manuscript.")
    lines.append("%% Requires: booktabs, url. No document preamble here.")
    lines.append(f"\\begin{{{env}}}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{tab:{name}}}")
    lines.append(f"\\begin{{tabular}}{{{spec}}}")
    lines.append("\\toprule")
    # Headers are authored in this file, so they are already valid LaTeX and
    # pass through verbatim; only a bare column name needs escaping.
    head = " & ".join(headers[c] if c in headers
                      else (c if "$" in c or "\\" in c else tex_escape(c))
                      for c in tdf.columns)
    lines.append(head + r" \\")
    lines.append("\\midrule")
    for _, row in tdf.iterrows():
        lines.append(" & ".join(fmt(row[c], nd, raw=c in raw_columns)
                                for c in tdf.columns) + r" \\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    full_note = note
    if not C.INCLUDE_LUNG_CANCER:
        full_note += " " + C.LUNG_CANCER_EXCLUSION_REASON
    lines.append(f"\\begin{{tablenotes}}\n\\footnotesize\n{full_note}\n\\end{{tablenotes}}")
    lines.append(f"\\end{{{env}}}")
    (C.TABLES_TEX / f"{name}.tex").write_text("\n".join(lines) + "\n")
    print(f"  wrote tables/csv/{name}.csv and tables/tex/{name}.tex  ({len(df)} rows)")


# ==========================================================================
# Shared helpers
# ==========================================================================

def bootstrap_run_mean_ci(
    values: np.ndarray, *, seed: int, n_resamples: int = 20_000
) -> tuple[float, float]:
    """Percentile 95% CI for the mean across independent attack repetitions."""
    values = np.asarray(values, dtype=float)
    if values.ndim != 1 or len(values) < 2 or not np.isfinite(values).all():
        raise ValueError("run-level bootstrap needs at least two finite outcomes")
    rng = np.random.default_rng(seed)
    means = rng.choice(values, size=(n_resamples, len(values)), replace=True).mean(axis=1)
    low, high = np.quantile(means, [0.025, 0.975])
    return float(low), float(high)


def _low_fpr_run_summary() -> pd.DataFrame:
    """Summarise exact 1%-FPR outcomes across LiRA shadow-calibration runs."""
    runs = L.load_all_lira_runs()
    runs = runs[
        (runs["variant"] == "dp")
        & np.isclose(pd.to_numeric(runs["epsilon"], errors="coerce"), C.EPS_TARGET)
    ].copy()
    if runs.empty:
        raise ValueError(f"no LiRA per-run rows found at epsilon={C.EPS_TARGET}")
    if "error" in runs and runs["error"].notna().any():
        failed = runs.loc[runs["error"].notna(), ["dataset_dir", "model", "run_seed"]]
        raise ValueError(f"LiRA has failed epsilon=1 runs; rerun them:\n{failed}")

    count_cols = ["op_1pct_tp", "op_1pct_fp", "op_1pct_tn", "op_1pct_fn"]
    for column in count_cols:
        values = pd.to_numeric(runs[column], errors="raise").to_numpy(float)
        if not np.equal(values, np.floor(values)).all() or (values < 0).any():
            raise ValueError(f"{column} must contain non-negative integer outcomes")
        runs[column] = values.astype(int)

    rows = []
    grouped = runs.groupby(["dataset_dir", "model"], sort=True)
    for group_index, ((dataset_dir, model), group) in enumerate(grouped):
        if group["run_seed"].duplicated().any():
            raise ValueError(f"duplicate LiRA run_seed for {dataset_dir}/{model}")
        target = pd.to_numeric(group["op_1pct_target_fpr"], errors="raise").to_numpy(float)
        if not np.allclose(target, C.RANDOM_FPR):
            raise ValueError(f"unexpected target FPR for {dataset_dir}/{model}")
        if set(group["op_1pct_selection_rule"]) != {
            "max_tpr_with_empirical_fpr_le_target"
        }:
            raise ValueError(f"unexpected ROC-point rule for {dataset_dir}/{model}")

        n_members = group["op_1pct_tp"] + group["op_1pct_fn"]
        n_nonmembers = group["op_1pct_fp"] + group["op_1pct_tn"]
        if n_members.nunique() != 1 or n_nonmembers.nunique() != 1:
            raise ValueError(f"evaluation-set sizes vary across {dataset_dir}/{model} runs")
        tpr = group["op_1pct_tp"].to_numpy(float) / n_members.to_numpy(float)
        fpr = group["op_1pct_fp"].to_numpy(float) / n_nonmembers.to_numpy(float)
        recorded_tpr = pd.to_numeric(group["op_1pct_tpr"], errors="raise").to_numpy(float)
        recorded_fpr = pd.to_numeric(group["op_1pct_fpr"], errors="raise").to_numpy(float)
        if not np.allclose(tpr, recorded_tpr) or not np.allclose(fpr, recorded_fpr):
            raise ValueError(f"stored rates disagree with integer outcomes for {dataset_dir}/{model}")
        if (fpr > C.RANDOM_FPR + 1e-15).any():
            raise ValueError(f"selected ROC point exceeds 1% FPR for {dataset_dir}/{model}")

        low, high = bootstrap_run_mean_ci(tpr, seed=20_260_829 + group_index)
        resolvable = group["op_1pct_fpr_resolvable"].astype(str).str.lower().eq("true")
        rows.append({
            "dataset": L.DIR_TO_DISPLAY[dataset_dir],
            "model": model,
            "lira_tpr_at_1pct": float(np.mean(tpr)),
            "lira_tpr_at_1pct_std": float(np.std(tpr)),
            "lira_tpr_at_1pct_ci_low": low,
            "lira_tpr_at_1pct_ci_high": high,
            "n_attack_runs": int(len(group)),
            "n_members_per_run": int(n_members.iloc[0]),
            "n_nonmembers_per_run": int(n_nonmembers.iloc[0]),
            "all_runs_fpr_resolvable": "yes" if resolvable.all() else "no",
            "low_fpr_ci_method": "run-level percentile bootstrap (20000 resamples)",
        })
    return pd.DataFrame(rows)


def _std_leakage() -> pd.DataFrame:
    """One row per (dataset, family) with every baseline leakage metric."""
    m = L.load_mia()
    std = m[m["variant"] == "standard"]

    yeom = (std[std["attack"] == "yeom"]
            [["dataset", "model", "advantage_mean", "advantage_std",
              "tpr_mean", "n_members", "n_nonmembers"]]
            .rename(columns={"advantage_mean": "yeom_advantage",
                             "advantage_std": "yeom_advantage_std",
                             "tpr_mean": "yeom_tpr"}))
    shokri = (std[std["attack"] == "shokri"]
              [["dataset", "model", "attack_auc_mean", "attack_auc_std"]]
              .rename(columns={"attack_auc_mean": "shokri_auc",
                               "attack_auc_std": "shokri_auc_std"}))
    lira = (std[std["attack"] == "lira"]
            [["dataset", "model", "attack_auc_mean", "attack_auc_std",
              "tpr_at_1pct", "tpr_at_1pct_std"]]
            .rename(columns={"attack_auc_mean": "lira_auc",
                             "attack_auc_std": "lira_auc_std",
                             "tpr_at_1pct": "lira_tpr_at_1pct",
                             "tpr_at_1pct_std": "lira_tpr_at_1pct_std"}))
    out = yeom.merge(shokri, on=["dataset", "model"]).merge(lira, on=["dataset", "model"])
    return out


def _order(df: pd.DataFrame) -> pd.DataFrame:
    """Stable dataset-by-N then family ordering."""
    ds_rank = {L.DIR_TO_DISPLAY[d]: i for i, d in enumerate(L.DATASET_DIRS)}
    fam_rank = {f: i for i, f in enumerate(L.FAMILIES)}
    d = df.copy()
    d["_ds"] = d["dataset"].map(ds_rank)
    key = "family" if "family" in d.columns else "model"
    d["_fm"] = d[key].map(lambda v: fam_rank.get(L.DP_TO_SHORT.get(v, v), 99))
    d = d.sort_values(["_ds", "_fm"]).drop(columns=["_ds", "_fm"])
    return d.reset_index(drop=True)


# ==========================================================================
# 1. dataset_characteristics                                   [48][49][50]
# ==========================================================================

def t_dataset_characteristics(conflicts: list) -> pd.DataFrame:
    u = L.load_utility()
    rows = []
    for ds in L.active_dataset_dirs():
        disp = L.DIR_TO_DISPLAY[ds]
        info = L.load_split_info(ds)
        ucsv = u[u["dataset"] == disp].iloc[0]

        # Cross-check N and d between the pickle and the consolidated CSV.
        n_samples, n_features = info["n_samples"], info["n_features"]
        if int(ucsv["n_samples"]) != n_samples:
            conflicts.append(
                f"n_samples for {disp}: {info['source']} = {n_samples} vs "
                f"{L.rel(C.UTILITY_CSV)} = {int(ucsv['n_samples'])}")
            n_samples = C.CONFLICT
        if int(ucsv["n_features"]) != n_features:
            conflicts.append(
                f"n_features for {disp}: {info['source']} = {n_features} vs "
                f"{L.rel(C.UTILITY_CSV)} = {int(ucsv['n_features'])}")
            n_features = C.CONFLICT

        counts = info["class_counts_all"]
        total = sum(counts.values())
        balance = "; ".join(f"{k}: {v} ({100 * v / total:.1f}%)"
                            for k, v in counts.items())
        k = info["n_classes"]
        task = ("Binary classification" if k == 2
                else f"{k}-class classification")

        synthetic, provenance = L.DATASET_PROVENANCE[ds]
        rows.append({
            "dataset": L.DIR_TO_LONG[ds],
            "dataset_dir": ds,
            "n_samples": n_samples,
            "n_features": n_features,
            "task": task,
            "n_classes": k,
            "class_balance": balance,
            "n_train": info["n_train"],
            "n_test": info["n_test"],
            "source_url": L.DATASET_URL[ds],
            "real_or_synthetic": synthetic,
            "provenance": provenance,
        })
    return pd.DataFrame(rows)


# ==========================================================================
# 2. baseline_accuracy_matrix                                      [11][51]
# ==========================================================================

def t_baseline_accuracy_matrix(conflicts: list) -> pd.DataFrame:
    u = L.load_utility()
    std = L.filter_datasets(u[u["variant"] == "standard"])
    m = L.load_mia()
    shokri = m[(m["attack"] == "shokri") & (m["variant"] == "standard")]

    rows = []
    for r in std.itertuples():
        fam = L.DP_TO_SHORT[r.model]
        sk = shokri[(shokri["dataset"] == r.dataset) & (shokri["model"] == fam)]
        exp_test = float(sk.iloc[0]["test_acc_mean"]) if len(sk) == 1 else np.nan
        exp_train = float(sk.iloc[0]["train_acc_mean"]) if len(sk) == 1 else np.nan
        rows.append({
            "dataset": r.dataset,
            "model": fam,
            "family": fam,
            "test_accuracy": float(r.accuracy_mean),
            "train_accuracy": float(r.train_accuracy_mean),
            "train_test_gap": float(r.train_accuracy_mean) - float(r.accuracy_mean),
            "test_accuracy_exported": exp_test,
            "train_accuracy_exported": exp_train,
            "train_test_gap_exported": exp_train - exp_test,
        })
    return _order(pd.DataFrame(rows))


# ==========================================================================
# 3. baseline_leakage_all_pairs                                        [10]
# ==========================================================================

def t_baseline_leakage_all_pairs(conflicts: list) -> pd.DataFrame:
    d = L.filter_datasets(_std_leakage())
    cols = ["dataset", "model",
            "yeom_advantage", "yeom_advantage_std",
            "shokri_auc", "shokri_auc_std",
            "lira_auc", "lira_auc_std",
            "lira_tpr_at_1pct", "lira_tpr_at_1pct_std"]
    return _order(d[cols])


# ==========================================================================
# 4. evaluation_set_sizes                                               [8]
# ==========================================================================

def t_evaluation_set_sizes(conflicts: list) -> pd.DataFrame:
    m = L.load_mia()
    rows = []
    for ds in L.active_dataset_dirs():
        disp = L.DIR_TO_DISPLAY[ds]
        sub = m[m["dataset"] == disp]

        # LiRA and Yeom both record the evaluation-set sizes; Shokri does not.
        sizes = {}
        for attack in ("lira", "yeom", "shokri"):
            a = sub[sub["attack"] == attack]
            vals = a[["n_members", "n_nonmembers"]].dropna().drop_duplicates()
            if len(vals) == 1:
                sizes[attack] = (int(vals.iloc[0]["n_members"]),
                                 int(vals.iloc[0]["n_nonmembers"]))
            elif len(vals) > 1:
                sizes[attack] = "MULTI"
        present = {k: v for k, v in sizes.items() if v != "MULTI"}
        distinct = set(present.values())
        if len(distinct) > 1:
            conflicts.append(
                f"evaluation-set sizes for {disp} differ across attacks: {present}")
            n_mem = n_non = C.CONFLICT
        else:
            n_mem, n_non = next(iter(distinct))

        # Cross-check against the split recorded in processed_data.pkl.
        info = L.load_split_info(ds)
        if not isinstance(n_mem, str) and (n_mem, n_non) != (info["n_train"], info["n_test"]):
            conflicts.append(
                f"evaluation-set sizes for {disp}: attacks report "
                f"({n_mem}, {n_non}) but {info['source']} has "
                f"(n_train={info['n_train']}, n_test={info['n_test']})")

        if isinstance(n_mem, str):
            ratio = min_fpr = exceeds = C.CONFLICT
        else:
            ratio = n_mem / n_non
            min_fpr = 1.0 / n_non
            exceeds = "yes" if min_fpr > C.RANDOM_FPR else "no"

        rows.append({
            "dataset": disp,
            "dataset_dir": ds,
            "n_members": n_mem,
            "n_nonmembers": n_non,
            "member_to_nonmember_ratio": ratio,
            "min_resolvable_fpr": min_fpr,
            "min_resolvable_fpr_exceeds_1pct": exceeds,
            "sizes_recorded_by": ", ".join(sorted(present)) or
                                 C.MISSING.format(what="attack-reported set sizes"),
            "balanced_1to1_evaluation": "no (balanced == False on all 300 LiRA rows)",
        })
    return pd.DataFrame(rows)


# ==========================================================================
# 5. residual_leakage_eps1                                         [14][15]
# ==========================================================================

def t_residual_leakage_eps1(conflicts: list) -> pd.DataFrame:
    m = L.filter_datasets(L.load_mia())
    dp = m[(m["variant"] == "dp") & (m["epsilon"] == C.EPS_TARGET)]

    yeom = (dp[dp["attack"] == "yeom"]
            [["dataset", "model", "advantage_mean", "advantage_std", "n_members"]]
            .rename(columns={"advantage_mean": "yeom_advantage",
                             "advantage_std": "yeom_advantage_std"}))
    shokri = (dp[dp["attack"] == "shokri"]
              [["dataset", "model", "attack_auc_mean", "attack_auc_std"]]
              .rename(columns={"attack_auc_mean": "shokri_auc",
                               "attack_auc_std": "shokri_auc_std"}))
    lira = (dp[dp["attack"] == "lira"]
            [["dataset", "model", "attack_auc_mean", "attack_auc_std"]]
            .rename(columns={"attack_auc_mean": "lira_auc",
                             "attack_auc_std": "lira_auc_std"}))
    d = (yeom.drop(columns=["n_members"])
         .merge(shokri, on=["dataset", "model"])
         .merge(lira, on=["dataset", "model"])
         .merge(_low_fpr_run_summary(), on=["dataset", "model"]))

    d["epsilon"] = C.EPS_TARGET
    d["family"] = d["model"]
    d["model"] = d["model"].map(L.SHORT_TO_DP)
    d["random_guess_tpr"] = C.RANDOM_FPR
    d["ci_excludes_random"] = [
        ("yes" if (not isinstance(lo, str) and lo > C.RANDOM_FPR) else "no")
        for lo in d["lira_tpr_at_1pct_ci_low"]]

    cols = ["dataset", "model", "family", "epsilon",
            "yeom_advantage", "yeom_advantage_std",
            "shokri_auc", "shokri_auc_std",
            "lira_auc", "lira_auc_std",
            "lira_tpr_at_1pct", "lira_tpr_at_1pct_std",
            "lira_tpr_at_1pct_ci_low", "lira_tpr_at_1pct_ci_high",
            "n_attack_runs", "n_members_per_run", "n_nonmembers_per_run",
            "all_runs_fpr_resolvable", "low_fpr_ci_method",
            "random_guess_tpr", "ci_excludes_random"]
    return _order(d[cols])


# ==========================================================================
# 6. rho_by_epsilon                                                    [19]
# ==========================================================================

def t_rho_by_epsilon(conflicts: list) -> pd.DataFrame:
    src = L.load_rho_by_epsilon()
    eps = sorted(src["epsilon"].unique())
    rows = []
    for (subset, al, metric), grp in src.groupby(
            ["subset", "al_definition", "metric"], sort=False):
        g = grp.set_index("epsilon")
        row = {"subset": subset, "al_definition": al, "metric": metric,
               "n": int(g["n"].iloc[0])}
        for e in eps:
            if e in g.index:
                row[f"rho_eps_{e}"] = float(g.loc[e, "rho"])
                row[f"p_eps_{e}"] = float(g.loc[e, "p"])
            else:
                row[f"rho_eps_{e}"] = C.MISSING.format(what=f"rho at eps={e}")
                row[f"p_eps_{e}"] = C.MISSING.format(what=f"p at eps={e}")
        rows.append(row)
    return pd.DataFrame(rows)


def _rho_tex_view(df: pd.DataFrame) -> pd.DataFrame:
    """rho with a significance star, one column per epsilon."""
    eps = [c.replace("rho_eps_", "") for c in df.columns if c.startswith("rho_eps_")]
    out = {"subset": df["subset"], "al_definition": df["al_definition"],
           "metric": df["metric"], "n": df["n"]}
    for e in eps:
        r, p = df[f"rho_eps_{e}"], df[f"p_eps_{e}"]
        out[f"$\\varepsilon$={e}"] = [
            (v if isinstance(v, str)
             else f"{v:.3f}" + ("$^{*}$" if (not isinstance(q, str) and q < 0.05) else ""))
            for v, q in zip(r, p)]
    return pd.DataFrame(out)


# ==========================================================================
# 7. within_pair_correlations                                          [18]
# ==========================================================================

def t_within_pair_correlations(conflicts: list) -> pd.DataFrame:
    s = L.load_within_pair_summary()
    out = s.rename(columns={
        "median_rho": "median_rho", "iqr_low": "iqr_q1", "iqr_high": "iqr_q3"})
    out.insert(1, "n_epsilons_per_pair", 9)
    return out


# ==========================================================================
# 8. bound_violations                                              [3][33]
# ==========================================================================

def t_bound_violations(conflicts: list) -> pd.DataFrame:
    m = L.filter_datasets(L.load_mia())
    lira = m[(m["attack"] == "lira") & (m["variant"] == "dp")].copy()

    rows = []
    for r in lira.itertuples():
        bound = math.exp(float(r.epsilon)) * C.RANDOM_FPR
        tpr = float(r.tpr_at_1pct)
        if not (tpr > bound):
            continue
        rows.append({
            "dataset": r.dataset,
            "model": L.SHORT_TO_DP[r.model],
            "family": r.model,
            "epsilon": float(r.epsilon),
            "lira_tpr_at_1pct": tpr,
            "bound_exp_eps_times_fpr": bound,
            "ratio_tpr_over_bound": tpr / bound,
            "n_members": int(r.n_members),
            "n_nonmembers": int(r.n_nonmembers),
        })
    if not rows:
        return pd.DataFrame(columns=[
            "dataset", "model", "family", "epsilon", "lira_tpr_at_1pct",
            "bound_exp_eps_times_fpr", "ratio_tpr_over_bound", "n_members",
            "n_nonmembers"])
    return _order(pd.DataFrame(rows)).sort_values(
        "ratio_tpr_over_bound", ascending=False).reset_index(drop=True)


# ==========================================================================
# 9. config_inventory                                          [9][59][61]
# ==========================================================================

def t_config_inventory(conflicts: list) -> pd.DataFrame:
    d = L.filter_datasets(build_provenance())
    return _order(d)


# ==========================================================================
# Driver
# ==========================================================================

RUN_CI_NOTE = ("The LiRA interval is a deterministic percentile bootstrap of the "
               "mean across the saved attack repetitions (20,000 resamples). Each "
               "repetition contributes its observed integer TP/FN outcome at an "
               "actual ROC threshold whose empirical FPR is at most 1\\%; repeated "
               "evaluations of the same records are not pooled as independent people.")


def main() -> list[str]:
    conflicts: list[str] = []
    print("Building tables...")

    # --- 1 -----------------------------------------------------------------
    d1 = t_dataset_characteristics(conflicts)
    write_table(
        "dataset_characteristics", d1,
        caption=("Characteristics of the six clinical datasets. $N$, the feature count, "
                 "the class balance and the split sizes are read from each dataset's "
                 "\\texttt{data/processed\\_data.pkl}; the 80/20 split is stratified with "
                 "\\texttt{random\\_state=42}."),
        note=("Class balance is reported over the full dataset (train $+$ test). "
              "Whether each source is real clinical data or synthetically generated is "
              "not derivable from the source URL alone; the \\texttt{Real/synthetic} and "
              "\\texttt{Provenance} columns are as supplied directly by the authors "
              "(2026-08-13), not inferred by this pipeline. Kidney Stone Risk is recorded "
              "as \\texttt{Unknown} on both columns because the authors themselves do not "
              "know its provenance -- this is their own answer, not a gap in the pipeline."),
        tex_columns=["dataset", "n_samples", "n_features", "task", "class_balance",
                     "n_train", "n_test", "source_url", "real_or_synthetic", "provenance"],
        headers={"dataset": "Dataset", "n_samples": "$N$", "n_features": "$d$",
                 "task": "Task", "class_balance": "Class balance",
                 "n_train": "$n_{\\mathrm{train}}$", "n_test": "$n_{\\mathrm{test}}$",
                 "source_url": "Source", "real_or_synthetic": "Synthetic?",
                 "provenance": "Provenance"},
        col_spec="lrrlp{3.0cm}rrp{2.6cm}lp{3.0cm}",
        tex_df=d1.assign(source_url=[f"\\url{{{u}}}" for u in d1["source_url"]]),
        raw_columns={"source_url"})

    # --- 2 -----------------------------------------------------------------
    d2 = t_baseline_accuracy_matrix(conflicts)
    write_table(
        "baseline_accuracy_matrix", d2,
        caption=("Non-private (capacity-matched) baselines: test accuracy, train "
                 "accuracy and the train$-$test generalisation gap for every "
                 "dataset $\\times$ model family."),
        note=("\\texttt{test\\_accuracy} / \\texttt{train\\_accuracy} are the 30-run means "
              "from \\texttt{Results/dataset\\_results/consolidated\\_data.csv} "
              "(\\texttt{variant==standard}). The two \\texttt{\\_exported} columns are the "
              "accuracies of the single exported run-0 artefact that the membership "
              "inference attacks actually target, taken from the Shokri attack CSV. The "
              "two estimands differ by at most 0.010 accuracy; both are shown so that no "
              "choice is made silently. The gap columns are "
              "$\\mathrm{train} - \\mathrm{test}$ within a single source."),
        tex_columns=["dataset", "model", "test_accuracy", "train_accuracy",
                     "train_test_gap", "test_accuracy_exported",
                     "train_accuracy_exported", "train_test_gap_exported"],
        headers={"dataset": "Dataset", "model": "Model",
                 "test_accuracy": "Test acc.", "train_accuracy": "Train acc.",
                 "train_test_gap": "Gap",
                 "test_accuracy_exported": "Test acc. (exp.)",
                 "train_accuracy_exported": "Train acc. (exp.)",
                 "train_test_gap_exported": "Gap (exp.)"},
        col_spec="llrrrrrr")

    # --- 3 -----------------------------------------------------------------
    d3 = t_baseline_leakage_all_pairs(conflicts)
    write_table(
        "baseline_leakage_all_pairs", d3,
        caption=("Membership inference leakage against the 30 non-private targets "
                 "(6 datasets $\\times$ 5 model families), for all three attacks. "
                 "Each value is a mean over repeated attack runs, with its standard "
                 "deviation."),
        note=("Yeom advantage is $\\mathrm{TPR}-\\mathrm{FPR}$ at the per-record loss "
              "threshold; Shokri and LiRA AUC are attack ROC AUCs, for which 0.5 is "
              "chance; LiRA TPR@1\\% is the true-positive rate at a 1\\% false-positive "
              "rate. Source: "
              "\\texttt{Results/attack\\_results/consolidated\\_mia\\_data.csv}, "
              "\\texttt{variant==standard}."),
        tex_columns=["dataset", "model", "yeom_advantage", "yeom_advantage_std",
                     "shokri_auc", "shokri_auc_std", "lira_auc", "lira_auc_std",
                     "lira_tpr_at_1pct", "lira_tpr_at_1pct_std"],
        headers={"dataset": "Dataset", "model": "Model",
                 "yeom_advantage": "Yeom adv.", "yeom_advantage_std": "SD",
                 "shokri_auc": "Shokri AUC", "shokri_auc_std": "SD",
                 "lira_auc": "LiRA AUC", "lira_auc_std": "SD",
                 "lira_tpr_at_1pct": "LiRA TPR@1\\%", "lira_tpr_at_1pct_std": "SD"},
        col_spec="llrrrrrrrr")

    # --- 4 -----------------------------------------------------------------
    d4 = t_evaluation_set_sizes(conflicts)
    write_table(
        "evaluation_set_sizes", d4,
        caption=("Membership inference evaluation sets. The minimum resolvable false "
                 "positive rate is $1/n_{\\mathrm{nonmembers}}$; where it exceeds the "
                 "1\\% reference FPR, TPR@1\\% cannot be measured at its nominal "
                 "operating point."),
        note=("Members are the training split and non-members the held-out test split, "
              "so the evaluation sets are 4:1 imbalanced rather than the balanced 1:1 "
              "design the referee asks for. \\texttt{balance\\_members()} exists in "
              "\\texttt{Attack/LiRA/lira.py} but \\texttt{--balance} was never passed: "
              "\\texttt{balanced == False} on all 300 LiRA rows. Per-record scores are "
              "not persisted, so this cannot be corrected without re-running the "
              "attacks. The Shokri CSVs do not record set sizes at all; the values here "
              "come from the LiRA and Yeom CSVs, which agree with each other and with "
              "each dataset's \\texttt{processed\\_data.pkl}."),
        tex_columns=["dataset", "n_members", "n_nonmembers",
                     "member_to_nonmember_ratio", "min_resolvable_fpr",
                     "min_resolvable_fpr_exceeds_1pct"],
        headers={"dataset": "Dataset", "n_members": "$n_{\\mathrm{members}}$",
                 "n_nonmembers": "$n_{\\mathrm{nonmembers}}$",
                 "member_to_nonmember_ratio": "Ratio",
                 "min_resolvable_fpr": "Min.\\ resolvable FPR",
                 "min_resolvable_fpr_exceeds_1pct": "$>1\\%$?"},
        col_spec="lrrrrl")

    # --- 5 -----------------------------------------------------------------
    d5 = t_residual_leakage_eps1(conflicts)
    write_table(
        "residual_leakage_eps1", d5,
        caption=("Residual membership inference leakage against the DP targets at "
                 "$\\varepsilon = 1.0$, for all 30 dataset $\\times$ model pairs, with "
                 "run-level 95\\% bootstrap intervals on the LiRA TPR@1\\%."),
        note=(RUN_CI_NOTE + " The interval is placed on the LiRA TPR@1\\%, the worst-case "
              "rate the residual-leakage claim rests on. \\texttt{ci\\_excludes\\_random} "
              "is \\texttt{yes} only where the lower confidence limit lies above the "
              "1\\% chance rate. Source: "
              "\\texttt{Results/attack\\_results/consolidated\\_mia\\_data.csv}, "
              "\\texttt{variant==dp} and \\texttt{epsilon==1.0}."),
        tex_columns=["dataset", "model", "yeom_advantage", "shokri_auc", "lira_auc",
                     "lira_tpr_at_1pct", "lira_tpr_at_1pct_ci_low",
                     "lira_tpr_at_1pct_ci_high", "ci_excludes_random"],
        headers={"dataset": "Dataset", "model": "Model",
                 "yeom_advantage": "Yeom adv.", "shokri_auc": "Shokri AUC",
                 "lira_auc": "LiRA AUC", "lira_tpr_at_1pct": "LiRA TPR@1\\%",
                 "lira_tpr_at_1pct_ci_low": "CI low",
                 "lira_tpr_at_1pct_ci_high": "CI high",
                 "ci_excludes_random": "$>1\\%$?"},
        col_spec="llrrrrrrl")

    # --- 6 -----------------------------------------------------------------
    d6 = t_rho_by_epsilon(conflicts)
    _rho = _rho_tex_view(d6)
    write_table(
        "rho_by_epsilon", d6,
        caption=("Spearman $\\rho$ between accuracy loss and each leakage metric, "
                 "computed separately at each privacy budget across the 30 dataset "
                 "$\\times$ model pairs."),
        note=("Reproduced verbatim from "
              "\\texttt{analysis/correlation\\_stats/rho\\_by\\_epsilon.csv}; nothing is "
              "recomputed here. $^{*}$ marks $p<0.05$ (uncorrected); exact $p$-values "
              "are in the companion CSV. \\texttt{AL} is the accuracy-based loss and "
              "\\texttt{AL\\_balanced} the balanced-accuracy variant; the "
              "\\texttt{robustness\\_excluded\\_near\\_majority} subset drops pairs whose "
              "non-private baseline sits near the majority-class rate."),
        col_spec="lllr" + "r" * (len(_rho.columns) - 4), nd=3,
        tex_df=_rho, raw_columns={c for c in _rho.columns if c.startswith("$")})

    # --- 7 -----------------------------------------------------------------
    d7 = t_within_pair_correlations(conflicts)
    write_table(
        "within_pair_correlations", d7,
        caption=("Within-pair Spearman correlations between accuracy loss and leakage, "
                 "computed inside each of the 30 dataset $\\times$ model pairs across "
                 "the nine shared privacy budgets, then summarised across pairs."),
        note=("Reproduced verbatim from \\texttt{analysis/within\\_pair/summary.csv}; "
              "per-pair values are in "
              "\\texttt{analysis/within\\_pair/pair\\_correlations.csv}. One Shokri pair is "
              "undefined because its leakage metric is constant across $\\varepsilon$. "
              "Significance counts are uncorrected at $p<0.05$."),
        tex_columns=["metric", "n_pairs_total", "n_computable", "n_undefined",
                     "median_rho", "iqr_q1", "iqr_q3", "min_rho", "max_rho",
                     "n_significant_p05", "n_significant_negative",
                     "n_significant_positive"],
        headers={"metric": "Leakage metric", "n_pairs_total": "Pairs",
                 "n_computable": "Computable", "n_undefined": "Undef.",
                 "median_rho": "Median $\\rho$", "iqr_q1": "Q1", "iqr_q3": "Q3",
                 "min_rho": "Min", "max_rho": "Max",
                 "n_significant_p05": "$p<0.05$",
                 "n_significant_negative": "Sig.\\ $-$",
                 "n_significant_positive": "Sig.\\ $+$"},
        col_spec="lrrrrrrrrrrr", nd=3)

    # --- 8 -----------------------------------------------------------------
    d8 = t_bound_violations(conflicts)
    write_table(
        "bound_violations", d8,
        caption=("DP configurations whose measured LiRA TPR@1\\% exceeds the "
                 "$\\varepsilon$-DP upper bound $e^{\\varepsilon}\\cdot\\mathrm{FPR}$ at "
                 "$\\mathrm{FPR}=0.01$."),
        note=("This is a descriptive screening table only. A row appearing here is "
              "not by itself evidence that the "
              "privacy guarantee is violated: the bound is stated on a single "
              "attack's true-positive rate at a fixed operating point, the reported "
              "TPR is a mean over repeated attack runs, and the finite non-member set "
              "limits the resolution of the 1\\% FPR threshold (see "
              "Table~\\ref{tab:evaluation_set_sizes}). No confidence/exceedance claim "
              "is computed here."),
        tex_columns=["dataset", "model", "epsilon", "lira_tpr_at_1pct",
                     "bound_exp_eps_times_fpr", "ratio_tpr_over_bound",
                     "n_nonmembers"],
        headers={"dataset": "Dataset", "model": "Model",
                 "epsilon": "$\\varepsilon$",
                 "lira_tpr_at_1pct": "TPR@1\\%",
                 "bound_exp_eps_times_fpr": "$e^{\\varepsilon}\\cdot 0.01$",
                 "ratio_tpr_over_bound": "Ratio",
                 "n_nonmembers": "$n_{\\mathrm{nonmembers}}$"},
        col_spec="llrrrrr")

    # --- 9 -----------------------------------------------------------------
    d9 = t_config_inventory(conflicts)
    write_table(
        "config_inventory", d9,
        caption=("Training configuration inventory: non-private hyperparameters, the "
                 "DP mechanism, minibatch size where applicable, and wall-clock "
                 "training time for every dataset $\\times$ model family."),
        note=("Hyperparameters are parsed from the per-model "
              "\\texttt{*\\_report.json} files, which sit at inconsistent depths and are "
              "located by globbing beneath \\texttt{<DATASET>/<FAMILY>/}. Where a report "
              "carries no \\texttt{parameters} block, the values are transcribed instead "
              "from the corresponding notebook's constructor call, read as source without "
              "executing it; the \\texttt{*\\_hyperparameters\\_source} columns of the "
              "companion CSV record which of the two each cell came from. "
              "\\texttt{train\\_time\\_mean} / \\texttt{train\\_time\\_std} are the DP "
              "training times at $\\varepsilon=1.0$ from "
              "\\texttt{consolidated\\_data.csv}; \\texttt{std\\_train\\_time\\_s} is the "
              "non-private time. Library versions (NumPy, scikit-learn, PyTorch, Opacus, "
              "diffprivlib) are not recorded in any per-model report; they are taken from "
              "the exact (\\texttt{==}) pins resolved in this repository's "
              "\\texttt{pyproject.toml} / \\texttt{uv.lock}. \\texttt{pyproject.toml} pins "
              "only a floor on the interpreter (\\texttt{requires-python = \">=3.13\"}), "
              "and \\texttt{uv.lock} resolves against both cp313 and cp314 wheel sets "
              "without recording which one actually ran; \\texttt{version\\_python} is "
              "recorded as 3.13 on the authors' direct confirmation of the interpreter "
              "used. The full hyperparameter strings are in the companion CSV."),
        tex_columns=["dataset", "model", "dp_mechanism", "batch_size",
                     "std_train_time_s", "train_time_mean", "train_time_std"],
        headers={"dataset": "Dataset", "model": "Model",
                 "dp_mechanism": "DP mechanism", "batch_size": "Batch size",
                 "std_train_time_s": "Non-private time (s)",
                 "train_time_mean": "DP time (s)", "train_time_std": "SD"},
        col_spec="llp{4.4cm}p{2.2cm}rrr")

    # Persist for gaps.md; verify.py appends its own findings to the same file.
    C.LOGS.mkdir(parents=True, exist_ok=True)
    (C.LOGS / "_conflicts.json").write_text(json.dumps(conflicts, indent=2) + "\n")
    print(f"\n{len(conflicts)} conflict(s) recorded -> logs/_conflicts.json")
    return conflicts


if __name__ == "__main__":
    conf = main()
    if conf:
        print("\nCONFLICTS:")
        for c in conf:
            print("  -", c)
