"""Canonical naming + all input loading for the artifact pipeline.

This is the ONLY module that knows how names differ between files
(``DP-RF`` in the utility CSV vs ``RF`` in the attack CSVs, ``BCP`` on disk vs
``Breast Cancer`` in every consolidated table).  Every other module imports the
mapping from here.

Read-only: nothing in this module writes outside ``analysis/``.
"""

from __future__ import annotations

import json
import pickle
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

import config as C

# ==========================================================================
# Canonical names
# ==========================================================================

# Directory name on disk -> display name used in the consolidated CSVs.
DATASET_DIRS = ["GALLSTONE", "BCP", "CANCER_RISK",
                "KIDNEY_STONE", "LUNG_CANCER", "DIABETES"]

DIR_TO_DISPLAY = {
    "GALLSTONE": "Gallstone",
    "BCP": "Breast Cancer",
    "CANCER_RISK": "Cancer Risk",
    "KIDNEY_STONE": "Kidney Stone",
    "LUNG_CANCER": "Lung Cancer",
    "DIABETES": "Diabetes",
}
DISPLAY_TO_DIR = {v: k for k, v in DIR_TO_DISPLAY.items()}

# Longer names used in tables where the referee asked for the published title.
DIR_TO_LONG = {
    "GALLSTONE": "Gallstone Status",
    "BCP": "Breast Cancer Wisconsin (Diagnostic)",
    "CANCER_RISK": "Cancer Risk Prediction",
    "KIDNEY_STONE": "Kidney Stone Risk",
    "LUNG_CANCER": "Lung Cancer Risk Level",
    "DIABETES": "BRFSS 2015 Diabetes Health Indicators",
}

# Verbatim, as supplied. Do not modify or supplement.
DATASET_URL = {
    "GALLSTONE": "https://archive.ics.uci.edu/dataset/1150/gallstone-1",
    "BCP": "https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic",
    "CANCER_RISK": "https://www.kaggle.com/datasets/rabieelkharoua/cancer-prediction-dataset",
    "KIDNEY_STONE": "https://www.kaggle.com/datasets/omarayman15/kidney-stones",
    "LUNG_CANCER": "https://www.kaggle.com/datasets/himabindumarpini/lung-cancer-datasets",
    "DIABETES": ("https://www.kaggle.com/datasets/alexteboul/"
                 "diabetes-health-indicators-dataset?select="
                 "diabetes_binary_health_indicators_BRFSS2015.csv"),
}

# Real-vs-synthetic status and provenance, as supplied directly by the authors
# (2026-08-13) -- not derivable from the source URL alone, so not inferred by
# this pipeline. "Unknown" for Kidney Stone is the authors' own answer, not a
# gap: they do not know either.
DATASET_PROVENANCE = {
    "GALLSTONE": ("No", "Ankara VM Medical Park Hospital (Clinical Data)"),
    "BCP": ("No", "University of Wisconsin (FNA Images)"),
    "CANCER_RISK": ("Yes", "Synthetically generated by author"),
    "KIDNEY_STONE": ("Unknown", "Unknown"),
    "LUNG_CANCER": ("Yes", "Unverified (widely considered synthetic)"),
    "DIABETES": ("No", "CDC (Behavioral Risk Factor Surveillance System)"),
}

# Model family: SHORT is the canonical key used throughout this package.
FAMILIES = ["RF", "LR", "GNB", "SVM", "DNN"]

SHORT_TO_DP = {"RF": "DP-RF", "LR": "DP-LR", "GNB": "DP-GNB",
               "SVM": "DP-SVM", "DNN": "DP-DNN"}
DP_TO_SHORT = {v: k for k, v in SHORT_TO_DP.items()}

# Short code -> directory name under <DATASET>/
SHORT_TO_DIR = {"RF": "RandomForest", "LR": "LR", "GNB": "GaussianNB",
                "SVM": "SVM", "DNN": "DNN"}

# Short code -> file stem used by the report JSONs (dp_<stem>_report.json).
SHORT_TO_STEM = {"RF": "rf", "LR": "lr", "GNB": "gnb", "SVM": "svm", "DNN": "dnn"}

# DP mechanism per family (CLAUDE.md S4; corroborated by the report JSONs).
# Plain text (Greek letters, no LaTeX): build_tables.py renders ε/δ as math.
DP_MECHANISM = {
    "RF": "Exponential mechanism (split selection), pure ε-DP",
    "LR": "Objective perturbation (diffprivlib), pure ε-DP",
    "GNB": "Laplace perturbation of sufficient statistics, pure ε-DP",
    "SVM": "Objective perturbation, Chaudhuri et al. Alg. 2, pure ε-DP",
    "DNN": "DP-SGD (Opacus), Gaussian mechanism, (ε, δ)-DP",
}

# Attack name -> per-dataset ground-truth CSV, relative to REPO.
ATTACK_CSV = {
    "lira": ("Attack/LiRA/results/{ds}/{ds}_lira_results.csv"),
    "shokri": ("Attack/MIA_Shokri/results/{ds}/{ds}_results.csv"),
    "yeom": ("Attack/MIA_YEOM/results/{ds}/{ds}_mia_results.csv"),
}

LIRA_ROC_PNG = "Attack/LiRA/results/{ds}/{ds}_loglog_roc.png"


def active_dataset_dirs() -> list[str]:
    """Dataset dirs honouring ``INCLUDE_LUNG_CANCER``."""
    if C.INCLUDE_LUNG_CANCER:
        return list(DATASET_DIRS)
    return [d for d in DATASET_DIRS if d != "LUNG_CANCER"]


def active_displays() -> list[str]:
    return [DIR_TO_DISPLAY[d] for d in active_dataset_dirs()]


def filter_datasets(df: pd.DataFrame, col: str = "dataset") -> pd.DataFrame:
    """Drop Lung Cancer rows when the switch is off. ``col`` may hold either
    the display name or the directory name."""
    if C.INCLUDE_LUNG_CANCER:
        return df
    bad = {"Lung Cancer", "LUNG_CANCER"}
    return df[~df[col].isin(bad)].copy()


# ==========================================================================
# Primary inputs
# ==========================================================================

def load_utility() -> pd.DataFrame:
    """Results/dataset_results/consolidated_data.csv, verbatim."""
    return pd.read_csv(C.UTILITY_CSV)


def load_mia() -> pd.DataFrame:
    """Results/attack_results/consolidated_mia_data.csv, verbatim."""
    return pd.read_csv(C.MIA_CSV)


def load_attack_csv(attack: str, ds_dir: str) -> pd.DataFrame:
    """Per-dataset ground-truth attack CSV. Adds a ``dataset_dir`` column."""
    path = C.REPO / ATTACK_CSV[attack].format(ds=ds_dir)
    df = pd.read_csv(path)
    df["dataset_dir"] = ds_dir
    return df


def load_all_attack_csvs(attack: str) -> pd.DataFrame:
    return pd.concat([load_attack_csv(attack, d) for d in DATASET_DIRS],
                     ignore_index=True)


# ---- reused analysis outputs (never recomputed) ---------------------------

def load_within_pair_summary() -> pd.DataFrame:
    return pd.read_csv(C.WITHIN_PAIR / "summary.csv")


def load_within_pair_correlations() -> pd.DataFrame:
    return pd.read_csv(C.WITHIN_PAIR / "pair_correlations.csv")


def load_rho_by_epsilon() -> pd.DataFrame:
    return pd.read_csv(C.CORRELATION_STATS / "rho_by_epsilon.csv")


def load_robustness_excluded() -> pd.DataFrame:
    return pd.read_csv(C.CORRELATION_STATS / "robustness_excluded.csv")


def load_balanced_accuracy() -> pd.DataFrame:
    return pd.read_csv(C.CORRELATION_STATS / "balanced_accuracy.csv")


def load_majority_class_accuracy() -> pd.DataFrame:
    return pd.read_csv(C.CORRELATION_STATS / "majority_class_accuracy.csv")


def load_figure_input() -> pd.DataFrame:
    return pd.read_csv(C.RQ_STATS / "figure_input.csv")


def load_correlations() -> pd.DataFrame:
    return pd.read_csv(C.RQ_STATS / "correlations.csv")


# ==========================================================================
# processed_data.pkl -- class balance and split sizes ONLY
# ==========================================================================

class _Stub:
    """Placeholder for any non-numpy class inside the pickle.

    The processed_data.pkl files carry a fitted MinMaxScaler and a
    LabelEncoder.  We never touch either, and instantiating this stub in their
    place means unpickling does not import scikit-learn at all -- no estimator
    is ever constructed, which is exactly what the no-compute constraint asks
    for.
    """

    def __init__(self, *args, **kwargs):
        pass

    def __setstate__(self, state):
        pass


class _RestrictedUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module.startswith("numpy") or module == "builtins":
            return super().find_class(module, name)
        return _Stub


def load_split_info(ds_dir: str) -> dict:
    """n_train, n_test, n_features and class counts from processed_data.pkl.

    Reads y_train / y_test / X_train.shape and nothing else.
    """
    path = C.REPO / ds_dir / "data" / "processed_data.pkl"
    with open(path, "rb") as fh:
        blob = _RestrictedUnpickler(fh).load()

    y_tr = np.asarray(blob["y_train"]).ravel()
    y_te = np.asarray(blob["y_test"]).ravel()
    x_tr = np.asarray(blob["X_train"])
    x_te = np.asarray(blob["X_test"])

    def counts(y):
        return {str(k): int(v) for k, v in sorted(Counter(y.tolist()).items())}

    all_counts = Counter(y_tr.tolist()) + Counter(y_te.tolist())
    return {
        "dataset_dir": ds_dir,
        "n_train": int(x_tr.shape[0]),
        "n_test": int(x_te.shape[0]),
        "n_features": int(x_tr.shape[1]),
        "n_samples": int(x_tr.shape[0] + x_te.shape[0]),
        "n_classes": int(len(all_counts)),
        "class_counts_train": counts(y_tr),
        "class_counts_test": counts(y_te),
        "class_counts_all": {str(k): int(v) for k, v in sorted(all_counts.items())},
        "source": f"{ds_dir}/data/processed_data.pkl",
    }


def load_all_split_info() -> pd.DataFrame:
    return pd.DataFrame([load_split_info(d) for d in DATASET_DIRS])


# ==========================================================================
# Report JSONs -- globbed, because they sit at inconsistent depths
# ==========================================================================

def find_report(ds_dir: str, family: str, variant: str) -> Path | None:
    """Locate ``<std|dp>_<stem>_report.json`` for one (dataset, family).

    Globs beneath ``<DS>/<FAMILY_DIR>/`` at any depth, which covers
    ``BCP/RandomForest/`` (depth 2), ``BCP/LR/data/`` and
    ``*/SVM/output/`` (depth 3) alike.  Files prefixed ``old_`` are ignored,
    and the search is anchored on the model-family directory, so the stale
    duplicates under ``BCP/Result/data/`` are never picked up.
    """
    stem = SHORT_TO_STEM[family]
    root = C.REPO / ds_dir / SHORT_TO_DIR[family]
    if not root.is_dir():
        return None
    hits = [p for p in root.rglob(f"{variant}_{stem}_report.json")
            if not p.name.startswith("old_")]
    if not hits:
        return None
    # Deterministic when a family somehow has more than one: shallowest first.
    hits.sort(key=lambda p: (len(p.parts), str(p)))
    return hits[0]


def read_report(ds_dir: str, family: str, variant: str) -> dict | None:
    path = find_report(ds_dir, family, variant)
    if path is None:
        return None
    with open(path) as fh:
        data = json.load(fh)
    data["__path__"] = str(path.relative_to(C.REPO))
    return data


def rel(path: Path | str) -> str:
    """Repo-relative string for provenance columns."""
    return str(Path(path).resolve().relative_to(C.REPO))


# ==========================================================================
# Coverage report (stage 1 sanity check)
# ==========================================================================

def coverage_report() -> str:
    lines = []
    add = lines.append

    u = load_utility()
    m = load_mia()

    add("=" * 74)
    add("STAGE 1 COVERAGE REPORT")
    add("=" * 74)
    add(f"INCLUDE_LUNG_CANCER = {C.INCLUDE_LUNG_CANCER}   "
        f"UTILITY_LABEL = {C.UTILITY_LABEL!r}   RANDOM_FPR = {C.RANDOM_FPR}")
    add("")

    add(f"utility CSV  {C.UTILITY_CSV.relative_to(C.REPO)}  shape={u.shape}")
    add(f"  variants: {u['variant'].value_counts().to_dict()}")
    add(f"  datasets: {sorted(u['dataset'].unique())}")
    add(f"  models:   {sorted(u['model'].unique())}")
    dp = u[u["variant"] == "dp"]
    add(f"  DP rows with n_runs==30: {int((dp['n_runs'] == 30).sum())} / {len(dp)}")
    add(f"  DP rows with n_runs NaN: {int(dp['n_runs'].isna().sum())}")
    nrun_missing = (dp[dp["n_runs"].isna()]
                    .groupby(["dataset", "model"]).size().to_dict())
    add(f"    -> missing n_runs by (dataset, model): {nrun_missing}")
    add(f"  exported_model_accuracy blank on {int(dp['exported_model_accuracy'].isna().sum())} DP rows")
    blank = (dp[dp["exported_model_accuracy"].isna()]
             .groupby(["dataset", "model"]).size().to_dict())
    add(f"    -> {blank}")
    add("")

    add(f"MIA CSV      {C.MIA_CSV.relative_to(C.REPO)}  shape={m.shape}")
    add(f"  attack x variant: {m.groupby(['attack', 'variant']).size().to_dict()}")
    add(f"  models:   {sorted(m['model'].unique())}")
    add(f"  DP epsilon grid: {sorted(m[m['variant'] == 'dp']['epsilon'].unique())}")
    for attack in ("lira", "shokri", "yeom"):
        sub = m[m["attack"] == attack]
        nm = sub["n_members"].notna().sum()
        add(f"  {attack:6s}: rows={len(sub):4d}  n_members present on {nm}")
    add("")

    add("Per-dataset attack CSV row counts (ground truth):")
    for attack in ("lira", "shokri", "yeom"):
        counts = {}
        for d in DATASET_DIRS:
            try:
                counts[d] = len(load_attack_csv(attack, d))
            except FileNotFoundError:
                counts[d] = "MISSING"
        add(f"  {attack:6s}: {counts}")
    add("")

    add("Baseline (standard) join: 6 datasets x 5 families = 30 pairs")
    std_u = u[u["variant"] == "standard"]
    add(f"  utility standard rows: {len(std_u)}")
    for attack in ("lira", "shokri", "yeom"):
        std_m = m[(m["attack"] == attack) & (m["variant"] == "standard")]
        add(f"  {attack:6s} standard rows: {len(std_m)}")
    add("")

    add("Split info from processed_data.pkl (class balance / n_train / n_test):")
    si = load_all_split_info()
    for r in si.itertuples():
        add(f"  {r.dataset_dir:14s} N={r.n_samples:6d} d={r.n_features:3d} "
            f"K={r.n_classes} train={r.n_train:6d} test={r.n_test:6d} "
            f"counts={r.class_counts_all}")
    add("")

    add("Report JSON discovery (std / dp per dataset x family):")
    for d in DATASET_DIRS:
        row = []
        for f in FAMILIES:
            s = find_report(d, f, "std")
            p = find_report(d, f, "dp")
            row.append(f"{f}:{'S' if s else '-'}{'D' if p else '-'}")
        add(f"  {d:14s} {' '.join(row)}")
    add("")

    add("Reused analysis inputs:")
    for name, fn in [("d14_summary", load_within_pair_summary),
                     ("d14_pair_correlations", load_within_pair_correlations),
                     ("d15_rho_by_epsilon", load_rho_by_epsilon),
                     ("d15_robustness_excluded", load_robustness_excluded),
                     ("d15_balanced_accuracy", load_balanced_accuracy),
                     ("d15_majority_class_accuracy", load_majority_class_accuracy),
                     ("d16_figure_input", load_figure_input),
                     ("d16_correlations", load_correlations)]:
        add(f"  {name:30s} shape={fn().shape}")
    add("")

    add("LiRA log-log ROC PNGs:")
    for d in DATASET_DIRS:
        p = C.REPO / LIRA_ROC_PNG.format(ds=d)
        add(f"  {d:14s} {'present' if p.exists() else 'MISSING'}  {p.relative_to(C.REPO)}")
    add("=" * 74)
    return "\n".join(lines)


if __name__ == "__main__":
    print(coverage_report())
